### ISSUE TITLE
Https protocol not found

### ISSUE THREAD

**Issue by kristiyanP** [lipangit/JieCaoVideoPlayer#320]
W/IJKMEDIA: https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
E/IJKMEDIA: https://video.twimg.com/ext_tw_video/738019496116551680/pu/vid/240x240/ZG6g_t8w-FG62YLX.mp4: Protocol not found
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [24347]
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by lipangit** [comment]
https://github.com/Bilibili/ijkplayer  你到这里看看吧，播放引擎用的这个，他们的播放协议用的这个https://ffmpeg.org/ffmpeg-protocols.html

**Comment by Maragues** [comment]
I'm seeing the same issue after updating from 3.6.3 to 4.6.3

Rolling back for now

**Comment by lipangit** [comment]
https://github.com/Bilibili/ijkplayer/issues/1665

I think something wrong with ijkplayer, He should not make this decision

**Comment by AidanLaing** [comment]
Any way to fix this?

**Comment by kristiyanP** [comment]
1) fork the library if you have not done it yet
2) fork https://github.com/Bilibili/ijkplayer
3) read the README of ijkplayer
3) follow this guide ( http://tcking.github.io/2016/02/25/compile-ijkplayer-with-openssl )
    -> be sure to have all the generated files int the folders as described in the last step of the tutorial
4) change the dependencies of ijkplayer of your forked JieCaoVideoPlayer library with the newly generated ijkplayer dependencies

**Comment by Maragues** [comment]
@kristiyanP did you manage to make it work? I'm checking your fork and I can't find anything related.

I'm trying to compile ijkplayer with open-ssl. I've managed to compile my own ijkplayer-java-release.aar and JieCaoVideoPlayer/app/ runs fine and plays https:// videos.

When I include the *jiecaovideoplayer-release.aar* in my project it compiles ok but I get a 

    java.lang.NoClassDefFoundError: Failed resolution of: Lfm/jiecao/jcvideoplayer_lib/JCMediaManager;

Any hint?

I'm working on this branch https://github.com/Maragues/JieCaoVideoPlayer/tree/ijkplayer-openssl

**Comment by Maragues** [comment]
Ok, I've managed to make it work by also including *ijkplayer-java-release.aar* in my project
